apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apache2
  name: apache2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: apache2
  strategy: {}
  template:
    metadata:
      creationTimestamp: nulllabels:
        app: apache2
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
      
